//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Account
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Account()
    {
        this.Orders = new HashSet<Order>();
        this.Transactions = new HashSet<Transaction>();
        this.Vouchers = new HashSet<Voucher>();
    }

    public string PK_Account { get; set; }
    public string Account_Name { get; set; }
    public Nullable<decimal> Balance { get; set; }
    public byte FK_Account_Type { get; set; }
    public byte FK_Account_Category { get; set; }
    public Nullable<System.DateTime> Insert_Date { get; set; }
    public string FK_Insert_User { get; set; }
    public Nullable<System.DateTime> Update_Date { get; set; }
    public string FK_Update_User { get; set; }
    public Nullable<bool> Is_Delete { get; set; }
    public Nullable<System.DateTime> Delete_Date { get; set; }
    public string FK_Delete_User { get; set; }
    public decimal DP_sum { get; set; }
    public decimal cr_sum { get; set; }

    public virtual Account_Types Account_Types { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order> Orders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Transaction> Transactions { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Voucher> Vouchers { get; set; }
    public virtual Account_Categories Account_Categories { get; set; }
}

public partial class Account_Categories
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Account_Categories()
    {
        this.Accounts = new HashSet<Account>();
    }

    public byte PK_Account_Category { get; set; }
    public string Account_Category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Account> Accounts { get; set; }
}

public partial class Account_Types
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Account_Types()
    {
        this.Accounts = new HashSet<Account>();
    }

    public byte PK_Account_Type { get; set; }
    public string Account_Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Account> Accounts { get; set; }
}

public partial class AspNetRole
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AspNetRole()
    {
        this.AspNetUsers = new HashSet<AspNetUser>();
    }

    public string Id { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
}

public partial class AspNetUser
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AspNetUser()
    {
        this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
        this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
        this.Transactions = new HashSet<Transaction>();
        this.Transactions1 = new HashSet<Transaction>();
        this.Transactions2 = new HashSet<Transaction>();
        this.AspNetRoles = new HashSet<AspNetRole>();
    }

    public string Id { get; set; }
    public string Email { get; set; }
    public bool EmailConfirmed { get; set; }
    public string PasswordHash { get; set; }
    public string SecurityStamp { get; set; }
    public string PhoneNumber { get; set; }
    public bool PhoneNumberConfirmed { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    public bool LockoutEnabled { get; set; }
    public int AccessFailedCount { get; set; }
    public string UserName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Transaction> Transactions { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Transaction> Transactions1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Transaction> Transactions2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
}

public partial class AspNetUserClaim
{
    public int Id { get; set; }
    public string UserId { get; set; }
    public string ClaimType { get; set; }
    public string ClaimValue { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class AspNetUserLogin
{
    public string LoginProvider { get; set; }
    public string ProviderKey { get; set; }
    public string UserId { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class Customer
{
    public long PK_Customer { get; set; }
    public string Customer_Name { get; set; }
    public Nullable<long> FileNum { get; set; }
    public Nullable<long> IDCard { get; set; }
    public string Mobile1 { get; set; }
    public string Mobile2 { get; set; }
    public string Address { get; set; }
    public string Notes { get; set; }
    public string FK_Account { get; set; }
    public Nullable<byte> FK_Customer_Type { get; set; }
    public string FK_Insert_User { get; set; }
    public Nullable<System.DateTime> Insert_Date { get; set; }
    public Nullable<System.DateTime> Update_Date { get; set; }
    public string FK_Update_User { get; set; }
    public Nullable<bool> Is_Delete { get; set; }
    public Nullable<System.DateTime> Delete_Date { get; set; }
    public string FK_Delete_User { get; set; }
    public Nullable<decimal> Balance { get; set; }

    public virtual Customers_Type Customers_Type { get; set; }
}

public partial class Customers_Type
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customers_Type()
    {
        this.Customers = new HashSet<Customer>();
    }

    public byte PK_Customer_Type { get; set; }
    public string Customer_Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Customer> Customers { get; set; }
}

public partial class Item
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Item()
    {
        this.OrderItems = new HashSet<OrderItem>();
    }

    public int PK_Item { get; set; }
    public string Item_Name { get; set; }
    public decimal Item_Price { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderItem> OrderItems { get; set; }
}

public partial class Order
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {
        this.OrderItems = new HashSet<OrderItem>();
    }

    public long PK_Order { get; set; }
    public byte FK_Sales_Man { get; set; }
    public string OrderNo { get; set; }
    public string FK_Account { get; set; }
    public System.DateTime Order_Date { get; set; }
    public string Sponsor { get; set; }
    public string Sponsor_Info { get; set; }
    public string FK_Insert_User { get; set; }
    public Nullable<long> FK_Transaction { get; set; }
    public Nullable<System.DateTime> Insert_Date { get; set; }
    public Nullable<System.DateTime> Update_Date { get; set; }
    public string FK_Update_User { get; set; }
    public Nullable<bool> Is_Delete { get; set; }
    public Nullable<System.DateTime> Delete_Date { get; set; }
    public string FK_Delete_User { get; set; }
    public Nullable<decimal> GTotal { get; set; }
    public Nullable<decimal> Payment { get; set; }
    public string Notes { get; set; }
    public Nullable<long> FK_Voucher { get; set; }
    public Nullable<int> Voucher_Num { get; set; }

    public virtual Sales_Man Sales_Man { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderItem> OrderItems { get; set; }
    public virtual Account Account { get; set; }
}

public partial class OrderItem
{
    public long PK_OrderItem { get; set; }
    public long FK_Order { get; set; }
    public int FK_Item { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    public decimal LineValue { get; set; }

    public virtual Item Item { get; set; }
    public virtual Order Order { get; set; }
}

public partial class Sales_Man
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sales_Man()
    {
        this.Orders = new HashSet<Order>();
    }

    public byte PK_Sales_Man { get; set; }
    public string Sales_Man_Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Transaction
{
    public long PK_Transaction { get; set; }
    public byte FK_Transaction_Type { get; set; }
    public System.DateTime Transaction_Date { get; set; }
    public string FK_Account { get; set; }
    public string Transaction_Name { get; set; }
    public decimal Amount { get; set; }
    public string FK_Insert_User { get; set; }
    public Nullable<System.DateTime> Insert_Date { get; set; }
    public Nullable<byte> FK_Transaction_Status { get; set; }
    public Nullable<System.DateTime> Update_Date { get; set; }
    public string FK_Update_User { get; set; }
    public Nullable<bool> Is_Delete { get; set; }
    public Nullable<System.DateTime> Delete_Date { get; set; }
    public string FK_Delete_User { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
    public virtual AspNetUser AspNetUser1 { get; set; }
    public virtual AspNetUser AspNetUser2 { get; set; }
    public virtual Transaction_Types Transaction_Types { get; set; }
    public virtual Account Account { get; set; }
}

public partial class Transaction_Types
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Transaction_Types()
    {
        this.Transactions = new HashSet<Transaction>();
    }

    public byte PK_Transaction_Type { get; set; }
    public string Transaction_Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Transaction> Transactions { get; set; }
}

public partial class Voucher
{
    public long PK_Voucher { get; set; }
    public Nullable<byte> FK_Voucher_Type { get; set; }
    public Nullable<int> Voucher_Num { get; set; }
    public Nullable<System.DateTime> Voucher_Date { get; set; }
    public string FK_Account { get; set; }
    public string Voucher_Name { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public string FK_Insert_User { get; set; }
    public Nullable<long> FK_Transaction { get; set; }
    public Nullable<byte> FK_Transaction_Type { get; set; }
    public Nullable<byte> FK_Voucher_Status { get; set; }
    public Nullable<System.DateTime> Insert_Date { get; set; }
    public Nullable<System.DateTime> Update_Date { get; set; }
    public string FK_Update_User { get; set; }
    public Nullable<bool> Is_Delete { get; set; }
    public Nullable<System.DateTime> Delete_Date { get; set; }
    public string FK_Delete_User { get; set; }

    public virtual Voucher_Types Voucher_Types { get; set; }
    public virtual Account Account { get; set; }
}

public partial class Voucher_Types
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Voucher_Types()
    {
        this.Vouchers = new HashSet<Voucher>();
    }

    public byte PK_Voucher_Type { get; set; }
    public string Voucher_Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Voucher> Vouchers { get; set; }
}

public partial class Accounts_AddEdit_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Accounts_Delete_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Accounts_Insert_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Accounts_Update_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Customer_AddEdit_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Customer_Delete_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Customer_Select_Result
{
    public long PK_Customer { get; set; }
    public string Customer_Name { get; set; }
    public Nullable<long> FileNum { get; set; }
    public Nullable<long> IDCard { get; set; }
    public string Mobile1 { get; set; }
    public string Mobile2 { get; set; }
    public string Address { get; set; }
    public string Notes { get; set; }
    public string FK_Account { get; set; }
    public Nullable<byte> FK_Customer_Type { get; set; }
    public string FK_Insert_User { get; set; }
    public Nullable<System.DateTime> Insert_Date { get; set; }
    public Nullable<System.DateTime> Update_Date { get; set; }
    public string FK_Update_User { get; set; }
    public Nullable<bool> Is_Delete { get; set; }
    public Nullable<System.DateTime> Delete_Date { get; set; }
    public string FK_Delete_User { get; set; }
    public Nullable<decimal> Balance { get; set; }
}

public partial class Customer_Update_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Order_AddEdit_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Order_AddEdit1_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Order_Delete_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Order_Insert_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Order_Select_Result
{
    public long PK_Order { get; set; }
    public byte FK_Sales_Man { get; set; }
    public string OrderNo { get; set; }
    public string FK_Account { get; set; }
    public System.DateTime Order_Date { get; set; }
    public string Sponsor { get; set; }
    public string Sponsor_Info { get; set; }
    public string FK_Insert_User { get; set; }
    public Nullable<long> FK_Transaction { get; set; }
    public Nullable<System.DateTime> Insert_Date { get; set; }
    public Nullable<System.DateTime> Update_Date { get; set; }
    public string FK_Update_User { get; set; }
    public Nullable<bool> Is_Delete { get; set; }
    public Nullable<System.DateTime> Delete_Date { get; set; }
    public string FK_Delete_User { get; set; }
    public Nullable<decimal> GTotal { get; set; }
}

public partial class Order_Update_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class OrderItems_AddEdit_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class OrderItems_Insert_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class OrderItems_Select_Result
{
    public long PK_OrderItem { get; set; }
    public long FK_Order { get; set; }
    public int FK_Item { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    public decimal LineValue { get; set; }
}

public partial class OrderItems_Update_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}

public partial class Transactions_AddEdit_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Transactions_Insert_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Transactions_Select_Result
{
    public long PK_Transaction { get; set; }
    public byte FK_Transaction_Type { get; set; }
    public System.DateTime Transaction_Date { get; set; }
    public string FK_Account { get; set; }
    public string Transaction_Name { get; set; }
    public decimal Amount { get; set; }
    public string FK_Insert_User { get; set; }
    public Nullable<System.DateTime> Insert_Date { get; set; }
    public Nullable<byte> FK_Transaction_Status { get; set; }
    public Nullable<System.DateTime> Update_Date { get; set; }
    public string FK_Update_User { get; set; }
    public Nullable<bool> Is_Delete { get; set; }
    public Nullable<System.DateTime> Delete_Date { get; set; }
    public string FK_Delete_User { get; set; }
}

public partial class Vouchers_AddEdit_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Vouchers_Insert_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Vouchers_Select_Result
{
    public long PK_Voucher { get; set; }
    public Nullable<byte> FK_Voucher_Type { get; set; }
    public Nullable<int> Voucher_Num { get; set; }
    public Nullable<System.DateTime> Voucher_Date { get; set; }
    public string FK_Account { get; set; }
    public string Voucher_Name { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public string FK_Insert_User { get; set; }
    public Nullable<long> FK_Transaction { get; set; }
    public Nullable<byte> FK_Transaction_Type { get; set; }
    public Nullable<byte> FK_Voucher_Status { get; set; }
    public Nullable<System.DateTime> Insert_Date { get; set; }
    public Nullable<System.DateTime> Update_Date { get; set; }
    public string FK_Update_User { get; set; }
    public Nullable<bool> Is_Delete { get; set; }
    public Nullable<System.DateTime> Delete_Date { get; set; }
    public string FK_Delete_User { get; set; }
}
