//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Orders = new HashSet<Order>();
            this.Transactions = new HashSet<Transaction>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public string PK_Account { get; set; }
        public string Account_Name { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public byte FK_Account_Type { get; set; }
        public byte FK_Account_Category { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
        public string FK_Insert_User { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string FK_Update_User { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public string FK_Delete_User { get; set; }
        public decimal DP_sum { get; set; }
        public decimal cr_sum { get; set; }
    
        public virtual Account_Types Account_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
        public virtual Account_Categories Account_Categories { get; set; }
    }
}
