//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public long PK_Order { get; set; }
        public byte FK_Sales_Man { get; set; }
        public string OrderNo { get; set; }
        public string FK_Account { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Sponsor { get; set; }
        public string Sponsor_Info { get; set; }
        public string FK_Insert_User { get; set; }
        public Nullable<long> FK_Transaction { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string FK_Update_User { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public string FK_Delete_User { get; set; }
        public Nullable<decimal> GTotal { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public string Notes { get; set; }
        public Nullable<long> FK_Voucher { get; set; }
        public Nullable<int> Voucher_Num { get; set; }
    
        public virtual Sales_Man Sales_Man { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Account Account { get; set; }
    }
}
