//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long PK_Transaction { get; set; }
        public byte FK_Transaction_Type { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public string FK_Account { get; set; }
        public string Transaction_Name { get; set; }
        public decimal Amount { get; set; }
        public string FK_Insert_User { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
        public Nullable<byte> FK_Transaction_Status { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string FK_Update_User { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public string FK_Delete_User { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual Transaction_Types Transaction_Types { get; set; }
        public virtual Account Account { get; set; }
    }
}
